name: hia
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  nb_utils: ^7.0.3
  http: ^1.2.1
  provider: ^6.0.5

  google_fonts: ^6.2.1
  country_code_picker: ^3.0.0
  font_awesome_flutter: ^10.7.0
  
  flutter_snake_navigationbar: ^0.6.1
  flutter_rating_bar: ^4.0.0
  readmore: ^3.0.0
  timeline_tile: ^2.0.0
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
