name: hia
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.5.1
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.5
  nb_utils: ^5.0.8
  http: ^1.0.0
  geocoding: ^2.0.0
  lottie: ^1.0.1
  provider: ^6.0.5
  map_location_picker: ^1.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.15
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  country_code_picker: ^3.0.0
  font_awesome_flutter: ^10.7.0
  vector_math: ^2.1.0
  flutter_map: ^7.0.2
  flutter_svg: ^2.0.0+1
  flutter_snake_navigationbar: ^0.6.1
  flutter_rating_bar: ^4.0.0
  readmore: ^3.0.0
  google_maps_flutter_web: ^0.5.8
  google_maps_flutter: ^2.1.3
  timeline_tile: ^2.0.0
  permission_handler: ^10.2.0
  connectivity_plus: ^3.0.0
  flutter_facebook_auth: ^7.0.0
  dots_indicator: ^3.0.0
  shimmer: ^3.0.0
  gap: ^3.0.1
  device_preview: ^1.2.0
  intl: ^0.19.0
  url_launcher: ^6.0.12
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  icon_decoration: ^2.0.2
  fast_cached_network_image: ^1.2.9
  get: ^4.6.6
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.2
  analyzer: ^4.7.0

flutter:
  uses-material-design: true

  assets:
  - images/
  - assets/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
